#!/usr/bin/env python3
"""Generate the Codex Harness projection from canonical Claude configuration."""

from __future__ import annotations

import argparse
import base64
import json
import os
import re
import shlex
import shutil
import stat
import sys
from pathlib import Path
from typing import Any

from common import (
    SUPPORTED_EFFORTS,
    json_dump,
    mapped_model,
    parse_frontmatter,
    rule_scopes,
    sha256,
    toml_array,
    toml_string,
)


MARKER = "Generated by `aiworks codex`; do not edit by hand."
TOML_MARKER = f"# {MARKER}"
JSON_MARKER = MARKER
SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent.parent


class Projection:
    def __init__(self, check: bool = False, dry_run: bool = False) -> None:
        self.check = check
        self.dry_run = dry_run
        self.changed = 0
        self.drifts: list[str] = []
        # Drift a WRITE pass cannot resolve: a real path where a link belongs, a generated file
        # somebody has edited, a rules file whose scope only its author can decide. Kept apart
        # from ordinary drift because the two need different callers — ordinary drift is closed by
        # running this generator, and registering it as the fix for one of THESE gives a repair
        # pass that runs forever and fails every time.
        self.blocked: list[str] = []
        # Which repo the current pass is projecting. A drift line reads `.agents/skills is
        # missing or points somewhere else` — true for fourteen repos at once and actionable in
        # none of them, so the blocked list carries the target that raised it.
        self.target = ""
        self.notes: list[str] = []

    def drift(self, message: str, blocked: bool = False) -> None:
        self.drifts.append(message)
        if blocked:
            self.blocked.append(f"{self.target}: {message}" if self.target else message)
        print(f"  ! {message}")

    def note(self, message: str) -> None:
        self.notes.append(message)
        print(f"  - {message}")

    def ok(self, message: str) -> None:
        print(f"  ✓ {message}")

    def emit_text(self, path: Path, content: str, label: str, executable: bool = False) -> None:
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            if executable and not os.access(path, os.X_OK) and not self.check and not self.dry_run:
                path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            self.ok(label)
            return
        if self.check:
            self.drift(f"{label} is {'stale' if path.exists() else 'missing'}",
                       blocked=path.is_file() and not owned_file(path))
            return
        if path.exists() and path.is_file() and not owned_file(path):
            self.drift(f"{label} is user-authored; leaving {path} unchanged", blocked=True)
            return
        if self.dry_run:
            self.note(f"would write {label}")
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        temp = path.with_suffix(path.suffix + f".{os.getpid()}.tmp")
        temp.write_text(content, encoding="utf-8")
        temp.replace(path)
        if executable:
            path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        self.changed += 1
        self.ok(f"{label} written")

    def emit_bytes(self, path: Path, content: bytes, label: str, executable: bool = False) -> None:
        if path.is_file() and path.read_bytes() == content:
            if executable and not os.access(path, os.X_OK) and not self.check and not self.dry_run:
                path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            self.ok(label)
            return
        if self.check:
            self.drift(f"{label} is {'stale' if path.exists() else 'missing'}",
                       blocked=path.is_file() and not owned_file(path))
            return
        if path.exists() and path.is_file() and not owned_file(path):
            self.drift(f"{label} is user-authored; leaving {path} unchanged", blocked=True)
            return
        if self.dry_run:
            self.note(f"would write {label}")
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        temp = path.with_suffix(path.suffix + f".{os.getpid()}.tmp")
        temp.write_bytes(content)
        temp.replace(path)
        if executable:
            path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        self.changed += 1
        self.ok(f"{label} written")

    def link(self, path: Path, target: str, label: str) -> None:
        if path.is_symlink() and os.readlink(path) == target:
            self.ok(label)
            return
        if self.check:
            self.drift(f"{label} is missing or points somewhere else",
                       blocked=path.exists() or path.is_symlink())
            return
        if path.exists() or path.is_symlink():
            # NEVER deleted, and never "reconciled" by comparing contents either. Measured, the
            # hard way: some repos carry the canonical skills IN `.agents/skills` with
            # `.claude/skills/<skill>` symlinked back INTO it, so a byte-for-byte comparison of
            # the two trees compares every file with ITSELF, calls the tree a redundant copy, and
            # deleting it destroys the only copy on disk. Whatever is here, a person decides.
            self.drift(f"{label} is a real path, not the expected link -> {target}; "
                       "leaving it unchanged (its content, or where it is linked from, is a decision)",
                       blocked=True)
            return
        if self.dry_run:
            self.note(f"would link {label} -> {target}")
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.symlink_to(target)
        self.changed += 1
        self.ok(f"{label} -> {target}")


def owned_file(path: Path) -> bool:
    try:
        head = path.read_text(encoding="utf-8", errors="ignore")[:500]
    except OSError:
        return False
    return MARKER in head or JSON_MARKER in head


def generated_helper(source: Path) -> bytes:
    text = source.read_text(encoding="utf-8")
    marker = f"# {MARKER}\n# Canonical adapter source: scripts/codex/{source.name}\n"
    if text.startswith("#!"):
        first, rest = text.split("\n", 1)
        text = f"{first}\n{marker}{rest}"
    else:
        text = marker + text
    return text.encode()


def parse_repo_dirs(config: Path) -> list[str]:
    if not config.is_file():
        return []
    repos: list[str] = []
    in_products = in_repos = False
    current: dict[str, str] = {}

    def flush() -> None:
        if not current.get("url"):
            current.clear()
            return
        value = current.get("path") or re.sub(r"\.git$", "", current["url"]).rstrip("/").split("/")[-1]
        if value and value not in repos:
            repos.append(value)
        current.clear()

    for raw in config.read_text(encoding="utf-8").splitlines():
        if raw == "products:":
            in_products = True
            continue
        if in_products and re.match(r"^  - id:", raw):
            flush()
            in_repos = False
            continue
        if in_products and raw == "    repos:":
            in_repos = True
            continue
        if in_products and re.match(r"^    [A-Za-z_]", raw):
            flush()
            in_repos = False
            continue
        if in_repos and re.match(r"^      - ", raw):
            flush()
            raw = re.sub(r"^      - ", "", raw)
        elif not (in_repos and re.match(r"^        [A-Za-z_]", raw)):
            if re.match(r"^[A-Za-z_]", raw):
                flush()
                in_products = in_repos = False
            continue
        match = re.match(r"^\s*(url|path):\s*(.*?)\s*$", raw)
        if match:
            current[match.group(1)] = match.group(2).strip("'\"")
    flush()
    return repos


def encode_command(command: str) -> str:
    return base64.b64encode(command.encode()).decode()


def matcher_routes(matcher: str | None) -> list[tuple[str, str]]:
    matcher = matcher or "*"
    if matcher in {"", "*"}:
        return [("*", "preserve")]
    routes: list[tuple[str, str]] = []
    for item in matcher.split("|"):
        item = item.strip()
        if item == "Bash":
            route = ("^Bash$", "Bash")
        elif item in {"Read", "Grep", "Glob"}:
            route = ("^Bash$", item)
        elif item in {"Write", "Edit", "NotebookEdit"}:
            route = ("^(apply_patch|Write|Edit)$", "Edit")
        elif item == "Agent":
            route = ("^(Agent|spawn_agent)$", "Agent")
        elif item == "ExitPlanMode":
            continue
        else:
            route = (f"^{re.escape(item)}$", item)
        if route not in routes:
            routes.append(route)
    return routes


def hooks_json(settings_path: Path) -> str:
    settings = json.loads(settings_path.read_text(encoding="utf-8"))
    event_map = {
        "SessionStart": "SessionStart",
        "SessionEnd": "SessionEnd",
        "PreToolUse": "PreToolUse",
        "PermissionRequest": "PermissionRequest",
        "PostToolUse": "PostToolUse",
        "PostToolUseFailure": "PostToolUse",
        "UserPromptSubmit": "UserPromptSubmit",
        "Stop": "Stop",
        "SubagentStart": "SubagentStart",
        "SubagentStop": "SubagentStop",
        "PreCompact": "PreCompact",
        "PostCompact": "PostCompact",
    }
    output: dict[str, Any] = {"description": JSON_MARKER, "hooks": {}}
    seen: set[tuple[str, str, str]] = set()
    for source_event, groups in (settings.get("hooks") or {}).items():
        target_event = event_map.get(source_event)
        if not target_event:
            continue
        for group in groups or []:
            for target_matcher, source_tool in matcher_routes(group.get("matcher")):
                handlers: list[dict[str, Any]] = []
                for handler in group.get("hooks") or []:
                    if handler.get("type") != "command" or not handler.get("command"):
                        continue
                    command = str(handler["command"])
                    key = (target_event, target_matcher, command)
                    if key in seen:
                        continue
                    seen.add(key)
                    shim = '"$(git rev-parse --show-toplevel)/.codex/hooks/hook_shim.sh"'
                    call = f"{shim} {shlex.quote(source_event)} {shlex.quote(source_tool)} {shlex.quote(encode_command(command))}"
                    item: dict[str, Any] = {"type": "command", "command": call}
                    if handler.get("timeout") is not None:
                        timeout = handler["timeout"]
                        item["timeout"] = min(int(timeout), 3) if target_event == "SessionEnd" else timeout
                    handlers.append(item)
                if handlers:
                    output["hooks"].setdefault(target_event, []).append(
                        {"matcher": target_matcher, "hooks": handlers}
                    )

    rule_command = 'python3 "$(git rev-parse --show-toplevel)/.codex/hooks/rule_context.py"'
    output["hooks"].setdefault("SessionStart", []).append(
        {
            "matcher": "^(startup|resume|clear|compact)$",
            "hooks": [
                {
                    "type": "command",
                    "command": rule_command,
                    "additionalContextLimit": 8000,
                }
            ],
        }
    )
    output["hooks"].setdefault("PreToolUse", []).append(
        {
            "matcher": "^(Bash|apply_patch|Write|Edit)$",
            "hooks": [
                {
                    "type": "command",
                    "command": rule_command,
                    "additionalContextLimit": 8000,
                }
            ],
        }
    )
    output["hooks"].setdefault("PreToolUse", []).append(
        {
            "matcher": "*",
            "hooks": [
                {
                    "type": "command",
                    "command": 'python3 "$(git rev-parse --show-toplevel)/.codex/hooks/tool_guard.py"',
                    "timeout": 10,
                }
            ],
        }
    )
    return json_dump(output)


def compatibility_json(settings_path: Path | None, projection: Projection) -> str:
    source_events: list[str] = []
    if settings_path and settings_path.is_file():
        source_events = sorted((json.loads(settings_path.read_text(encoding="utf-8")).get("hooks") or {}).keys())
    event_map: dict[str, Any] = {
        "SessionStart": "SessionStart",
        "SessionEnd": "SessionEnd",
        "PreToolUse": "PreToolUse",
        "PermissionRequest": "PermissionRequest",
        "PostToolUse": "PostToolUse",
        "PostToolUseFailure": "PostToolUse",
        "UserPromptSubmit": "UserPromptSubmit",
        "Stop": "Stop",
        "SubagentStart": "SubagentStart",
        "SubagentStop": "SubagentStop",
        "PreCompact": "PreCompact",
        "PostCompact": "PostCompact",
        "PermissionDenied": {"folded_into": "PermissionRequest", "reason": "Codex has no post-denial event"},
        "Notification": {"folded_into": ["PermissionRequest", "Stop"], "reason": "attention and completion signals"},
    }
    unknown = [event for event in source_events if event not in event_map]
    for event in unknown:
        projection.drift(f"hooks: no Codex event mapping declared for {event}", blocked=True)
    return json_dump(
        {
            "_aiworks": JSON_MARKER,
            "hook_events": {event: event_map[event] for event in source_events if event in event_map},
            "native_agent_permissions": {
                "status": "conservative",
                "detail": "roles without canonical Write/Edit default to read-only, but parent live permissions override spawned agents; permission-sensitive work uses aiworks workflow",
            },
            "status_line": {
                "status": "native-presentation",
                "detail": "Codex supports ordered built-in footer items, not Claude's external multiline command",
            },
            "mcp_sse": {
                "status": "bridged",
                "detail": "canonical SSE endpoints use mcp-remote stdio only in the Codex projection",
            },
        }
    )


def required_skills(base: Path, values: list[str], projection: Projection, label: str) -> list[str]:
    result: list[str] = []
    for value in values:
        name = value.split(":")[-1]
        if not (base / ".claude" / "skills" / name / "SKILL.md").is_file():
            projection.drift(f"{label}: required skill {value!r} has no canonical .claude/skills/{name}/SKILL.md",
                             blocked=True)
            continue
        if name not in result:
            result.append(name)
    return result


def agent_toml(base: Path, source: Path, projection: Projection) -> tuple[str, str]:
    frontmatter, body = parse_frontmatter(source)
    name = str(frontmatter.get("name") or source.stem)
    description = str(frontmatter.get("description") or "")
    if not description:
        projection.drift(f"agents/{source.name}: description is required", blocked=True)
    model = mapped_model(str(frontmatter.get("model") or ""))
    effort = str(frontmatter.get("effort") or "")
    if effort and effort not in SUPPORTED_EFFORTS:
        projection.drift(f"agents/{source.name}: unsupported Codex effort {effort!r}", blocked=True)
        effort = ""
    skills = required_skills(base, [str(item) for item in frontmatter.get("skills", [])], projection, f"agents/{source.name}")
    tools = {str(item) for item in frontmatter.get("tools", [])}
    max_turns = frontmatter.get("maxTurns")
    additions: list[str] = []
    if skills:
        additions.append(
            "## Required startup skills\n\n"
            "Before doing role work, load and follow these projected skills: "
            + ", ".join(f"`{skill}`" for skill in skills)
            + ". Missing or unreadable skill content is a hard failure."
        )
    if max_turns:
        additions.append(
            f"## Execution ceiling\n\nThe canonical role ceiling is {max_turns} agentic turns. "
            "Hand off a complete checkpoint before reaching it; never die mid-step."
        )
    instructions = body.rstrip() + ("\n\n" + "\n\n".join(additions) if additions else "") + "\n"
    if "'''" in instructions:
        projection.drift(f"agents/{source.name}: developer instructions contain unsupported TOML literal delimiter",
                         blocked=True)
        instructions = instructions.replace("'''", "’”")

    lines = [TOML_MARKER, f"name = {toml_string(name)}", f"description = {toml_string(description)}"]
    if model:
        lines.append(f"model = {toml_string(model)}")
    if effort:
        lines.append(f"model_reasoning_effort = {toml_string(effort)}")
    if frontmatter.get("permissionMode") == "plan" or not {"Write", "Edit"}.intersection(tools):
        lines.append('sandbox_mode = "read-only"')
    lines.extend(["developer_instructions = '''", instructions.rstrip(), "'''", ""])
    return name, "\n".join(lines)


def mcp_toml(mcp_path: Path) -> list[str]:
    if not mcp_path.is_file():
        return []
    data = json.loads(mcp_path.read_text(encoding="utf-8"))
    lines: list[str] = []
    for name, server in (data.get("mcpServers") or {}).items():
        table = f"mcp_servers.{name}"
        lines.extend([f"[{table}]"])
        if server.get("type") == "sse" and server.get("url"):
            # Codex supports streamable HTTP, not the deprecated SSE client transport. Keep the
            # canonical endpoint for Claude/Cursor and bridge only this projection through stdio.
            lines.append('command = "npx"')
            lines.append(f"args = {toml_array(['-y', 'mcp-remote@latest', str(server['url'])])}")
            lines.append("startup_timeout_sec = 30")
        elif server.get("command"):
            lines.append(f"command = {toml_string(str(server['command']))}")
            if server.get("args"):
                lines.append(f"args = {toml_array([str(item) for item in server['args']])}")
        if server.get("url") and server.get("type") != "sse":
            lines.append(f"url = {toml_string(str(server['url']))}")
        if server.get("cwd"):
            lines.append(f"cwd = {toml_string(str(server['cwd']))}")
        headers = dict(server.get("headers") or {})
        auth = str(headers.pop("Authorization", ""))
        match = re.fullmatch(r"Bearer \$\{([A-Za-z_][A-Za-z0-9_]*)\}", auth)
        if match:
            lines.append(f"bearer_token_env_var = {toml_string(match.group(1))}")
        elif auth:
            headers["Authorization"] = auth
        env_headers: dict[str, str] = {}
        static_headers: dict[str, str] = {}
        for key, value in headers.items():
            env_match = re.fullmatch(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", str(value))
            if env_match:
                env_headers[str(key)] = env_match.group(1)
            else:
                static_headers[str(key)] = str(value)
        if server.get("env"):
            lines.append("")
            lines.append(f"[{table}.env]")
            for key, value in sorted(server["env"].items()):
                lines.append(f"{key} = {toml_string(str(value))}")
        if env_headers:
            lines.append("")
            lines.append(f"[{table}.env_http_headers]")
            for key, value in sorted(env_headers.items()):
                lines.append(f"{toml_string(key)} = {toml_string(value)}")
        if static_headers:
            lines.append("")
            lines.append(f"[{table}.http_headers]")
            for key, value in sorted(static_headers.items()):
                lines.append(f"{toml_string(key)} = {toml_string(value)}")
        lines.append("")
    return lines


def config_toml(base: Path) -> str:
    lines = [
        TOML_MARKER,
        "#:schema https://developers.openai.com/codex/config-schema.json",
        "",
        "[features]",
        "hooks = true",
        "",
        "[agents]",
        "enabled = true",
        "max_concurrent_threads_per_session = 8",
        "",
        "[tui]",
        "status_line = [",
        '  "model-with-reasoning",',
        '  "current-dir",',
        '  "git-branch",',
        '  "context-used",',
        '  "total-input-tokens",',
        '  "context-window-size",',
        "]",
        "",
    ]
    lines.extend(mcp_toml(base / ".mcp.json"))
    return "\n".join(lines).rstrip() + "\n"


def rules_index(root: Path, base: Path, repo_dirs: list[str], is_root: bool, projection: Projection) -> str:
    rules: list[dict[str, Any]] = []
    source_root = root if is_root else base

    def collect(owner: Path, prefix: str = "") -> None:
        source_dir = owner / ".claude" / "rules"
        if not source_dir.is_dir():
            return
        for path in sorted(source_dir.rglob("*.md")):
            try:
                scopes = rule_scopes(path)
            except ValueError as exc:
                projection.drift(str(exc), blocked=True)
                continue
            rel = path.relative_to(source_root).as_posix()
            prefixed = [f"{prefix}/{scope}" if prefix else scope for scope in scopes]
            rules.append({"source": rel, "scopes": prefixed, "sha256": sha256(path)})

    collect(base)
    if is_root:
        for repo in repo_dirs:
            owner = root / repo
            if owner.is_dir():
                collect(owner, repo)
    return json_dump({"_aiworks": JSON_MARKER, "rules": rules})


def prune_generated_agents(base: Path, expected: set[str], projection: Projection) -> None:
    directory = base / ".codex" / "agents"
    if not directory.is_dir():
        return
    for path in directory.glob("*.toml"):
        if path.name in expected or not owned_file(path):
            continue
        if projection.check:
            projection.drift(f"agents/{path.name} is stale")
        elif projection.dry_run:
            projection.note(f"would remove stale agents/{path.name}")
        else:
            path.unlink()
            projection.changed += 1
            projection.ok(f"removed stale agents/{path.name}")


def project_target(root: Path, base: Path, repo_dirs: list[str], is_root: bool, projection: Projection) -> None:
    label = "workspace root" if is_root else base.name
    projection.target = label
    print(f"\n==> Codex projection: {label}")
    if (base / "CLAUDE.md").is_file():
        projection.link(base / "AGENTS.md", "CLAUDE.md", "AGENTS.md")
    if (base / ".claude" / "skills").is_dir():
        projection.link(base / ".agents" / "skills", "../.claude/skills", ".agents/skills")

    hooks_dir = base / ".codex" / "hooks"
    for source_name, target_name, executable in (
        ("common.py", "common.py", False),
        ("tool_guard.py", "tool_guard.py", True),
        ("rule_context.py", "rule_context.py", True),
        ("hook_shim.sh", "hook_shim.sh", True),
    ):
        projection.emit_bytes(
            hooks_dir / target_name,
            generated_helper(SCRIPT_DIR / source_name),
            f"hooks/{target_name}",
            executable=executable,
        )

    settings = base / ".claude" / "settings.json"
    if settings.is_file():
        projection.emit_text(base / ".codex" / "hooks.json", hooks_json(settings), "hooks.json")
    else:
        projection.note("no .claude/settings.json; no source hooks to project")

    projection.emit_text(base / ".codex" / "config.toml", config_toml(base), "config.toml")
    projection.emit_text(
        base / ".codex" / "generated" / "rules.json",
        rules_index(root, base, repo_dirs, is_root, projection),
        "generated/rules.json",
    )
    projection.emit_text(
        base / ".codex" / "generated" / "compatibility.json",
        compatibility_json(settings if settings.is_file() else None, projection),
        "generated/compatibility.json",
    )

    expected: set[str] = set()
    agents_dir = base / ".claude" / "agents"
    if agents_dir.is_dir():
        for source in sorted(agents_dir.glob("*.md")):
            name, content = agent_toml(base, source, projection)
            filename = f"{name}.toml"
            expected.add(filename)
            projection.emit_text(base / ".codex" / "agents" / filename, content, f"agents/{filename}")
    prune_generated_agents(base, expected, projection)


def remove_target(base: Path, projection: Projection) -> None:
    projection.target = base.name
    print(f"\n==> Remove Codex projection: {base.name}")
    candidates = [
        base / ".codex" / "config.toml",
        base / ".codex" / "hooks.json",
        base / ".codex" / "generated" / "rules.json",
        base / ".codex" / "generated" / "compatibility.json",
        base / ".codex" / "hooks" / "common.py",
        base / ".codex" / "hooks" / "tool_guard.py",
        base / ".codex" / "hooks" / "rule_context.py",
        base / ".codex" / "hooks" / "hook_shim.sh",
    ]
    candidates.extend((base / ".codex" / "agents").glob("*.toml") if (base / ".codex" / "agents").is_dir() else [])
    for path in candidates:
        if not path.exists() or not owned_file(path):
            continue
        if projection.check:
            projection.drift(f"generator-owned {path.relative_to(base)} remains")
        elif projection.dry_run:
            projection.note(f"would remove {path.relative_to(base)}")
        else:
            path.unlink()
            projection.changed += 1
            projection.ok(f"removed {path.relative_to(base)}")
    skill_link = base / ".agents" / "skills"
    if skill_link.is_symlink() and os.readlink(skill_link) == "../.claude/skills":
        if projection.check:
            projection.drift("generator-owned .agents/skills remains")
        elif projection.dry_run:
            projection.note("would remove .agents/skills")
        else:
            skill_link.unlink()
            projection.changed += 1
            projection.ok("removed .agents/skills")
    if not projection.check and not projection.dry_run:
        for directory in (
            base / ".codex" / "generated",
            base / ".codex" / "hooks",
            base / ".codex" / "agents",
            base / ".codex",
            base / ".agents",
        ):
            try:
                directory.rmdir()
            except OSError:
                pass


def resolve_targets(root: Path, config: Path, names: list[str]) -> tuple[list[tuple[Path, bool]], list[str]]:
    repo_dirs = parse_repo_dirs(config)
    if not names:
        targets = [(root, True)] + [(root / repo, False) for repo in repo_dirs if (root / repo).is_dir()]
        return targets, repo_dirs
    targets: list[tuple[Path, bool]] = []
    for name in names:
        if name in {".", root.name}:
            targets.append((root, True))
            continue
        path = Path(name)
        if not path.is_absolute():
            path = root / name
        targets.append((path.resolve(), path.resolve() == root.resolve()))
    return targets, repo_dirs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("targets", nargs="*", help="repo directory/name; default root + declared repos")
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--config", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--dry-run", "-n", action="store_true")
    parser.add_argument("--remove", action="store_true")
    args = parser.parse_args()

    root = args.root.resolve()
    config = (args.config or root / "workspace.config.yaml").resolve()
    projection = Projection(check=args.check, dry_run=args.dry_run)
    targets, repo_dirs = resolve_targets(root, config, args.targets)
    if not config.is_file():
        projection.note(f"{config.name} is absent; projecting the canonical workspace root only")
        targets = [(root, True)] if not args.targets else targets

    for base, is_root in targets:
        if not base.is_dir():
            projection.drift(f"target does not exist: {base}", blocked=True)
            continue
        if args.remove:
            remove_target(base, projection)
        else:
            project_target(root, base, repo_dirs, is_root, projection)

    print(f"\nCodex projection: changed={projection.changed} drift={len(projection.drifts)} notes={len(projection.notes)}")
    for message in projection.blocked:
        print(f"  needs a person: {message}")
    # --check IS THE GATE, and only --check. A reconcile or a preview reports what it could not
    # do and exits 0: it did everything it was allowed to do, and the projector interface
    # (docs/agents/harnesses.md) promises a preview "without writing or failing on expected
    # drift". Failing them instead made `aiworks sync` warn "could not reconcile Harness
    # projections" on every run of a workspace holding one hand-written AGENTS.md, and made
    # `doctor --fix` print `✗ failed` for a pass that had written every surface it was allowed
    # to — the same "owner command that can never close its finding" this change exists to
    # remove, just relocated.
    #
    # Under --check the exit code carries what the caller needs to route the finding:
    #   0  in sync
    #   1  drift a reconcile WILL close — run the generator
    #   2  drift it will not: a real path where the canonical link belongs, a generated file
    #      somebody edited, a rules file with no frontmatter, a source defect only its author
    #      can settle. Whoever is repairing must hand these to a person, not to a command.
    if not args.check:
        return 0
    if projection.blocked:
        return 2
    return 1 if projection.drifts else 0


if __name__ == "__main__":
    raise SystemExit(main())
